name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd end-to-end-cicd-aws
          git pull origin main

          cd app
          docker stop $(docker ps -q --filter ancestor=myflaskapp) || true
          docker rm $(docker ps -aq --filter ancestor=myflaskapp) || true

          docker build -t myflaskapp .
          docker run -d -p 5000:5000 myflaskapp
